require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'EgyMovies' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  use_flipper!
  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end
end
